channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - astropy >=5
    - astroquery
    - ccdproc
    - ginga
    - ipywidgets
    - bottleneck
    - photutils >=1
    - matplotlib
    - pandas
    - gatspy
    - pyyaml
    - astrowidgets
    - ipyfilechooser
    - reducer
    - reproject
    - sphinx-astropy
