channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.10
    - astropy >=5
    - astroquery
    - ccdproc
    - ginga
    - ipywidgets
    - bottleneck
    - photutils >=1
    - matplotlib
    - pandas
    - gatspy
    - pyyaml
    - astrowidgets
    - ipyautoui
    - pydantic<2
    - reducer
    - reproject
    - sphinx-astropy
