channels:
    - conda-forge
    - defaults
dependencies:
    - astropy
    - matplotlib
    - reducer
    - photutils
    - astroquery
    - reproject
    - bottleneck
    - astrowidgets
    - ccdproc
    - sphinx-astropy

