name: Test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.10","3.11"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-astropy wheel cython

    - name: Install stellarphot
      run: |
        pip install .

    - name: Install batman
      run: |
        pip install batman-package

    - name: Run tests
      run: |
        pytest -v stellarphot

  documentation:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Install stellarphot
        run: |
          pip install .

      - name: Install batman
        run: |
          pip install batman-package

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Run tests
        run: |
          tox -e build_docs
